INSERT INTO Specializations([Name], [Description])
VALUES('Allergist', 'conducts the diagnosis and treatment of allergic conditions'),
('Anesthesiologist', 'treats chronic pain syndromes; administers anesthesia and monitors the patient during surgery'),
('Cardiologist', 'treats heart disease'),
('Dermatologist', 'treats skin diseases, including some skin cancers'),
('Gastroenterologist', 'treats stomach disorders'),
('Hematologist / Oncologist', 'treats diseases of the blood and blood-forming tissues(oncology including cancer and other tumors)'),
('Internal Medicine Physician', 'treats diseases and disorders of internal structures of the body'),
('Nephrologist', 'treats kidney diseases'),
('Neurologist', 'treats diseases and disorders of the nervous system'),
( 'Neurosurgeon', 'conducts surgery of the nervous system'),
('Obstetrician', 'treats women during pregnancy and childbirth'),
('Gynecologist', 'treats diseases of the female reproductive system and genital tract'),
('Nurse-Midwifery', 'manages a woman''s health care, especially during pregnancy, delivery, and the postpartum period'),
('Occupational Medicine Physician', 'diagnoses and treats work-related disease or injury'),
('Ophthalmologist', 'treats eye defects, injuries, and diseases'),
('Oral and Maxillofacial Surgeon', 'surgically treats diseases, injuries, and defects of the hard and soft tissues of the face, mouth, and jaws'),
('Orthopaedic Surgeon', 'preserves and restores the function of the musculoskeletal system'),
('Otolaryngologist (Head and Neck Surgeon)', 'treats diseases of the ear, nose, and throat, and some diseases of the head and neck, including facial plastic surgery'),
('Pathologist', 'diagnoses and treats the study of the changes in body tissues and organs which cause or are caused by disease'),
('Pediatrician', 'treats infants, toddlers, children and teenagers'),
('Plastic Surgeon', 'restores, reconstructs, corrects or improves in the shape and appearance of damaged body structures, especially the face'),
('Podiatrist', 'provides medical and surgical treatment of the foot'),
('Psychiatrist', 'treats patients with mental and emotional disorders'),
('Pulmonary Medicine Physician', 'diagnoses and treats lung disorders'),
('Radiation Onconlogist', 'diagnoses and treats disorders with the use of diagnostic imaging, including X-rays, sound waves, radioactive substances, and magnetic fields'),
('Diagnostic Radiologist', 'diagnoses and medically treats diseases and disorders of internal structures of the body'),
('Rheumatologist', 'treats rheumatic diseases, or conditions characterized by inflammation, soreness and stiffness of muscles, and pain in joints and associated structures'),
('Urologist', 'diagnoses and treats the male and female urinary tract and the male reproductive system')

